### ISSUE TITLE
Lumen

### ISSUE THREAD

**Issue by j3rrey** [mpociot/laravel-test-factory-helper#43]
Trying to run this in Lumen 5.8.* gives me:
Exception: No hint path defined for [test-factory-helper].

Any idea on how to fix it would be greatly appreciated

**Comment by jasonmccreary** [comment]
Curious if this would resolve your issue - https://github.com/mpociot/laravel-test-factory-helper/pull/30

**Comment by j3rrey** [comment]
Nah didn't help :( 
Still the same error

**Comment by jasonmccreary** [comment]
Can you post the full stack trace. I don't use Lumen so it's not something I can easily test.

**Comment by j3rrey** [comment]
I've nailed down the problem to the createFactory method will investigate further.
Here is the stacktrace:
`
#0 /app/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments('test-factory-he...')\n
#1 /app/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView('test-factory-he...')\n
#2 /app/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find('test-factory-he...')\n
#3 /app/app/Console/Commands/Vendor/GenerateCommand.php(380): Illuminate\View\Factory->make('test-factory-he...', Array)\n
#4 /app/app/Console/Commands/Vendor/GenerateCommand.php(166): App\Console\Commands\Vendor\GenerateCommand->createFactory(Object(App\Models\FailedOrder))\n
#5 /app/app/Console/Commands/Vendor/GenerateCommand.php(91): App\Console\Commands\Vendor\GenerateCommand->generateFactory(Object(App\Models\FailedOrder))\n
#6 [internal function]: App\Console\Commands\Vendor\GenerateCommand->handle()\n
#7 /app/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array(Array, Array)\n
#8 /app/vendor/illuminate/container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()\n
#9 /app/vendor/illuminate/container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(App\Application), Array, Object(Closure))\n
#10 /app/vendor/illuminate/container/Container.php(576): Illuminate\Container\BoundMethod::call(Object(App\Application), Array, Array, NULL)\n
#11 /app/vendor/illuminate/console/Command.php(183): Illuminate\Container\Container->call(Array)\n
#12 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))\n
#13 /app/vendor/illuminate/console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))\n
#14 /app/vendor/symfony/console/Application.php(921): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#15 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Vendor\GenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#16 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#17 /app/vendor/illuminate/console/Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#18 /app/vendor/laravel/lumen-framework/src/Console/Kernel.php(115): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#19 /app/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))\n
#20 {main}
`
